name: huxt

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - astropy=5.1
  - h5py==3.1.0
  - httplib2==0.19.0
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.3
  - jupyterlab=3.3.2
  - matplotlib=3.3.4
  - moviepy==1.0.1
  - numpy=1.20.1
  - numba=0.53.0
  - pandas=1.2.3
  - packaging=21.3
  - pip=21.1
  - pyhdf=0.10.5
  - pytables=3.6.1
  - pytest=7.1.2
  - scipy=1.10.0
  - sunpy=4.0.4
  - urllib3=1.26.8
  
